# gz topic published by Sensors plugin
# - ros_topic_name: "scan"
#   gz_topic_name: "scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS

# # gz topic published by Sensors plugin (Camera)
# - ros_topic_name: "camera/camera_info"
#   gz_topic_name: "camera/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS
  
  # gz teleop
- ros_topic_name: "cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "gz.msgs.Twist"
  direction: GZ_TO_ROS